### ISSUE TITLE
Touchpad scrolling not working on some devices

### ISSUE THREAD

**Issue by Darthagnon** [stnkl/EverythingToolbar#20] opened 2020-11-05 11:43 UTC
Dunno if it's just me, but touchpad scrolling seems to no longer work in the list, either (Windows Precision Touchpad). 

Originally, I opened this issue just for this: 

``` 
Latest version 0.4.0, Win10 v1709. Search results can appear twice (not sure if all do). I've confirmed that they do not appear twice in regular Everything. See attached screenshot.
```
but the screenshot I tried to take disappeared, and then the same search term showed only single results, so I couldn't replicate it.

**Comment by stnkl** [comment] 2020-11-05 20:36
Regarding the touchpad problem: Which version did it work with for you? I just tried this on my laptop and none of the releases seem to have had working touchpad scrolling.

**Comment by Darthagnon** [comment] 2020-11-06 12:31
I'll double-check - I didn't notice it not working until the latest version 0.4.0.

**Comment by anonimuos** [comment] 2021-01-06 07:09
I can confirm it's not working as of 0.6.1. I don't know when it last worked. Mouse scroll wheel works 100% and arrow keys also but touchpad two single scroll doesn't work.

Also since Home and End affect the text box (which is perfect, that's how I would expect it), it would be nice if Page up and page down made the results list scroll (instead of moving the text box cursor) :)

Btw I want to thank the developer for promptly fixing bugs, adding so many nice features/enhancements and making regular releases. As of 0.6.1, it's a very fine and useful app! Everyone I have shown it to prefers it over Windows 10 Search box.

**Comment by stnkl** [comment] 2021-01-06 14:29
> Btw I want to thank the developer for promptly fixing bugs, adding so many nice features/enhancements and making regular releases. As of 0.6.1, it's a very fine and useful app! Everyone I have shown it to prefers it over Windows 10 Search box.

Thank you very much!

> Also since Home and End affect the text box (which is perfect, that's how I would expect it), it would be nice if Page up and page down made the results list scroll (instead of moving the text box cursor) :)

I agree. That would help users who are affected by the touchpad issue and is a good idea in general.

I did some googling and found multiple threads about the same issue with Stardock fences (like @Darthagnon mentioned). Seems to be caused by the fact that EverythingToolbar gets embedded into the taskbar. When running it as a regular window application the touchpad scrolling works as expected.

I don't really want to implement a hacky workaround (if there is one) because I only have one laptop (which is affected by the issue too) and can't test it on a non-affected laptop. That's why I marked this issue as "help wanted" in hopes of somebody else chiming in with experience regarding similar issues.

**Comment by Michael82548** [comment] 2021-01-30 19:05
It's not working for me either. I do not use Stardock. I have a precision trackpad and here is the info:

Everything-1.4.1.1005.x64-Setup.exe

64-bit operating system, x64-based processor
Edition	Windows 10 Home
Version	20H2
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

Touchpad info:
![image](https://user-images.githubusercontent.com/53535277/106365483-ea300780-6303-11eb-987c-4ea21c26d95b.png)

**Comment by Michael82548** [comment] 2021-02-07 21:59
@stnkl

**Comment by stnkl** [comment] 2021-02-07 22:16
@Michael82548 I am aware of the issue but don't know any solution right now. Please don't bump issues.

**Comment by stnkl** [comment] 2021-02-12 23:28
How are you using your touchpad for scrolling? Are you using two-finger scrolling?

The Synaptics driver doesn't seem to send scroll wheel events correctly to some applications. [Two-finger-scroll](https://github.com/awahlig/two-finger-scroll) is using the Synaptics SDK to interpret its own scroll events which do work within EverythingToolbar. I could implement something similar but it might get tricky for non-standard user settings like inverted scrolling or scrolling by sliding on the side of the touchpad. Also I am not sure about the SDK license.

**Comment by Michael82548** [comment] 2021-02-12 23:38
Yes. I am using 2 finger scrolling.

**Comment by anonimuos** [comment] 2021-03-07 08:27
If it's of any help, here's something new I have observed about my two laptops. Both laptops have Synaptics touchpads and both run Windows 10, but one of them has the Windows Precision Touchpad drivers and the other has proprietary Synaptics drivers. 

On the laptop with the proprietary Synaptics drivers, two-finger touchpad scrolling works absolutely fine with Everything Toolbar (and also with Open Shell/Classic Shell which is how I discovered this).

But on the laptop with Windows Precision Touchpad drivers, it is broken. So I suspect this driver itself has something broken or missing.

**Comment by stnkl** [comment] 2021-03-08 19:19
> But on the laptop with Windows Precision Touchpad drivers, it is broken. So I suspect this driver itself has something broken or missing.

Does scrolling work in Open Shell/Classic Shell with this driver?

I have a working implementation which uses the SDK to get scroll events from the device directly. Looks like I have to check for the precision touchpad drivers specifically to enable this workaround.

I will get to this eventually but I will be busy for the next few weeks.

**Comment by anonimuos** [comment] 2021-03-10 03:52
> Does scrolling work in Open Shell/Classic Shell with this driver?
> 
> I have a working implementation which uses the SDK to get scroll events from the device directly. Looks like I have to check for the precision touchpad drivers specifically to enable this workaround.
> 
> I will get to this eventually but I will be busy for the next few weeks.

No, scrolling doesn't work in either Open Shell or Everything Toolbar with the Precision Touchpad laptop driver. Glad to know you found a workaround :) Thank you for your continued development efforts on Everything Toolbar.

**Comment by Darthagnon** [comment] 2021-03-11 15:07
Maybe once implemented, [Open Shell](https://github.com/Open-Shell/Open-Shell-Menu) and Stardock Fences could implement similar fixes in their products.

[Here's the main, most recent thread on the Stardock forums about problems scrolling in Stardock Fences](https://forums.stardock.com/497894/i-am-still-having-the-problem-that-on-some-of-my-touchpadscomputers-i-cant-) (I posted there before)

**Comment by stnkl** [comment] 2021-05-08 14:05
Could you guys please try this latest (experimental) version? It includes the workaround for Synaptics touchpads (or at least the one _I_ own). I did not do any checks for Windows precision touchpad drivers yet. So it might cause problems with the proprietary Synaptics drivers now (@anonimuos). I wasn't able to figure out how to remove the precision touchpad driver so I couldn't really test that yet. Hopefully you guys can help me out with testing that. 😊

Please keep in mind that this is just a dirty workaround so expect it to feel different than normal scrolling but at least it enables the user to use the touchpad in the first place. Let me know how it works for you!

[EverythingToolbar-0.6.3.1.msi.zip](https://github.com/stnkl/EverythingToolbar/files/6445948/EverythingToolbar-0.6.3.1.msi.zip)

**Comment by Michael82548** [comment] 2021-05-13 01:49
Did not fix the issue for me

**Comment by anonimuos** [comment] 2021-05-13 07:57
Sorry for the late response. I was busy.

With this version it is now broken with both kinds of drivers. On the laptop with Synaptics drivers, touchpad scrolling is now broken and very erratic (it worked with earlier version). On the one with Precision Touchpad drivers, it doesn't work at all.

**Comment by stnkl** [comment] 2021-05-14 09:48
> With this version it is now broken with both kinds of drivers. On the laptop with Synaptics drivers, touchpad scrolling is now broken and very erratic (it worked with earlier version). On the one with Precision Touchpad drivers, it doesn't work at all.

Does the laptop scroll down when moving the fingers down?

Anyway, I was hoping it would fix the combination of Synaptics touchpad and precision mousepad driver for everyone. I was able to fix it for my laptop but it seems to be more hardware specific than that. So unfortunately I don't think I will be able to fix this without access to more hardware. That might explain why Stardock Fences and other applications haven't fixed this in apparently years.

**Comment by anonimuos** [comment] 2021-05-15 07:03
It scrolls erratically sometimes up, sometimes down. As if it's being scrolled against its will.

**Comment by stnkl** [comment] 2021-06-24 23:08
I will now close this issue with "won't fix" as this is a dependency issue and I don't own the hardware to fix it for everyone.

**Closed by stnkl** 2021-06-24 23:08 UTC
Labels: bug, dependency issue

**Comment by Nuzza** [comment] 2023-03-16 01:57
Is there any new information on this? Will this ever be resolved? It irritates me that two-finger scrolling does not work despite working perfectly when using a mouse wheel, or that two-finger scrolling works fine in Everything's window (not EverythingToolbar).

I usually have to grab the scroll bar while using my laptop's trackpad to scroll; EverythingToolbar would be perfect if this issue was resolved.
