### ISSUE TITLE
EverythingToolbar is not displayed in the search box in the taskbar

### ISSUE THREAD

**Issue by gadfeldan** [stnkl/EverythingToolbar#57] opened 2020-12-27 08:33 UTC
I followed the instructions and I installed as admin and enabled EverythingToolbar. Indeed, the toolbar is installed, but unfortunately it is not displayed in the search box in the taskbar.

**Comment by Horst12** [comment] 2020-12-27 10:06
The Toolbar has its own icon and is not related to the Windows search field in the taskbar.

**Comment by gadfeldan** [comment] 2020-12-27 10:27
The Toolbar icon is also not displayed.

**Comment by stnkl** [comment] 2020-12-27 10:42
- Which version of Windows are you running?
- Is there any output in `EverythingToolbar.log`?
- Does the checkmark on the toolbar entry "Everything Toolbar" stay after enabling the toolbar or does it uncheck itself?

**Comment by gadfeldan** [comment] 2020-12-27 11:02
I'm running Windows 10 64 bit Home.
[EverythingToolbar.log](https://github.com/stnkl/EverythingToolbar/files/5744436/EverythingToolbar.log)
 The checkmark on the toolbar entry "Everything Toolbar" stay after enabling the toolbar.

**Comment by stnkl** [comment] 2020-12-27 11:11
It looks like a running Everything instance could not be found. Did you install Everything from voidtools.com? It has to be running in the background. The Lite version is not supported and can't be used with EverythingToolbar.

**Comment by Horst12** [comment] 2020-12-27 14:14
> 
> 
> It looks like a running Everything instance could not be found. Did you install Everything from voidtools.com? It has to be running in the background. The Lite version is not supported and can't be used with EverythingToolbar.

The entry "Everything version 0.0.0 is not supported" is also on my system !
But for me its runs perfect and finds the running actual Everything version.
In some previous Toolbar version it reported the correct version in the log.

**Comment by gadfeldan** [comment] 2020-12-27 14:23
So what can be done? Is there a solution?

**Comment by Horst12** [comment] 2020-12-27 14:25
> 
> 
> So what can be done? Is there a solution?

What is your reported Everything version (Help / About in Everything)

**Comment by gadfeldan** [comment] 2020-12-27 15:53
1.4.1.1002

**Comment by stnkl** [comment] 2020-12-30 22:04
@gadfeldan Please unlock the taskbar (taskbar context menu), enable EverythingToolbar so that the checkbox stays checked and take a screenshot of the complete taskbar (left to right).

**Comment by gadfeldan** [comment] 2020-12-31 04:01
![InkedSnipaste_2020-12-31_05-53-06(In English)_LI](https://user-images.githubusercontent.com/75246555/103393819-857b6480-4b2d-11eb-9ff3-073690ebba48.jpg)
![Snipaste_2020-12-31_05-48-06 (In Hebrew)](https://user-images.githubusercontent.com/75246555/103393830-8c09dc00-4b2d-11eb-90d3-d1ccf9a3db9e.png)
I understood what the problem was. I use Windows in the Hebrew language (writing from right to left). Indeed, the Everything Tool bar icon does not appear in the Hebrew language. When I switch Windows to English (left-to-right writing) the Everything Tool bar icon appears.

**Comment by stnkl** [comment] 2020-12-31 08:47
Yes, there is a known issue (#15) with deskbands not showing correctly with RTL languages.

**Comment by gadfeldan** [comment] 2020-12-31 08:59
I hope you can fix this in one of the following updates.

**Comment by stnkl** [comment] 2020-12-31 11:38
For now you should be able to open the popup by pressing <kbd>Win</kbd>+<kbd>Alt</kbd>+<kbd>S</kbd>.

Closing this issue since it's a duplicate of #15.

**Closed by stnkl** 2020-12-31 11:38 UTC

**Comment by gadfeldan** [comment] 2020-12-31 12:29
Thank you very much.

**Comment by Horst12** [comment] 2021-01-02 17:55
0.6.1-beta1 now shows the correct Everything version in the log file

**Comment by stnkl** [comment] 2021-01-02 18:00
> 0.6.1-beta1 now shows the correct Everything version in the log file

Which is really interesting because I did not change anything in that regard.

**Comment by gadfeldan** [comment] 2021-01-03 11:54
interesting.
