### ISSUE TITLE
.NET Event log

### ISSUE THREAD

**Issue by johnny712712** [stnkl/EverythingToolbar#125] opened 2021-03-30 16:35 UTC
Noticed Event ID 1026 for .NET Framework

`Application: Explorer.EXE
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at EverythingToolbar.ToolbarControl.OnUnloaded(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastUnloadedEvent(System.Object)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
`

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Client
    CBS    REG_DWORD    0x1
    Install    REG_DWORD    0x1
    InstallPath    REG_SZ    C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
    Release    REG_DWORD    0x70bf6
    Servicing    REG_DWORD    0x0
    TargetVersion    REG_SZ    4.0.0
    Version    REG_SZ    4.7.03190

**Comment by stnkl** [comment] 2021-03-30 21:40
When and where exactly do you get this output? Is there anything in the log file at `%TEMP%\EverythingToolbar.log`?

**Comment by stnkl** [comment] 2021-06-09 21:10
Hi, I was not able to reproduce this so far. Would it be possible for you to give some more details on this?

**Comment by stnkl** [comment] 2021-06-16 19:18
I'm closing this issue for now since it's lacking necessary information. I'll reopen if needed.

**Comment by johnny712712** [comment] 2021-06-16 19:19
The timing, I was just looking into this and trying to find information. Sorry for the delay, It is hard to say, We run this in an Terminal server environment and it doesn't provide if it was tied to a particular user. Or any system logs that i can see

**Comment by stnkl** [comment] 2021-06-17 12:26
Was this a one time occurence or does it happen repeatedly?

**Comment by johnny712712** [comment] 2021-06-17 14:07
No it happens all the time. There will be multiple entries of this in a day, and with 10- 20 users on the server at once, hard to say who caused the error and how. I am trying to monitor on a server with less users and seeing if we can isolate it somehow.

**Comment by johnny712712** [comment] 2021-09-10 15:12
Hey @stnkl 
Since the release of 0.71 this error has not occurred on any terminal servers or local machines. :)

**Comment by stnkl** [comment] 2021-09-10 23:20
Happy to hear that! I'm honestly not sure why but I'll close this issue again then. Let me know in case the problem reappears!

**Closed by stnkl** 2021-09-10 23:20 UTC
Labels: bug, info/repro needed
