### ISSUE TITLE
Installer is blocked by Edge

### ISSUE THREAD

**Issue by yudapedia** [stnkl/EverythingToolbar#200] opened 2021-09-06 04:29 UTC
Downloading 0.7.2 installer using Microsoft Edge resulting an error.
Screenshot: https://i.imgur.com/OdEzKfD.png

**Comment by Horst12** [comment] 2021-09-06 07:26
There is noothing bad in it.
Its just to new for Edge.
Unblock it.

**Comment by stnkl** [comment] 2021-09-06 21:05
As Horst said this is not an issue with the installer itself. I think it's caused by Microsoft Smartscreen which checks for known safe executables which this new release is not one of yet. It will probably be marked as safe once enough people download it.

**Closed** 2021-09-06 21:06 UTC
Labels: question
