### ISSUE TITLE
face lag 

### ISSUE THREAD

**Issue by khaleeq11** [stnkl/EverythingToolbar#137] opened 2021-04-10 05:18 UTC
I have i5 6300U I face a short time of lag while opening everything toolbar it is more than while opening windows own search I think it is more annoying

**Comment by Horst12** [comment] 2021-04-10 08:23
There is no opening time for me.
I start to type into the toolbar and it displays the results with no delay
as Everything runs in background.

**Comment by stnkl** [comment] 2021-04-10 08:31
Try disabling animations. Otherwise duplicate of #95.

**Closed by stnkl** 2021-04-10 08:31 UTC

**Comment by khaleeq11** [comment] 2021-04-10 08:47
yeah same problem animation is not smooth as windows own serach it feel like a lag

**Comment by Fayyaadh** [comment] 2021-08-22 11:30
I just installed this yesterday and it was fine but today I see that the animation is slightly laggy right at the beginning.
