### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by EbinVarghese1511** [stnkl/EverythingToolbar#254] opened 2022-09-20 02:36 UTC
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/stnkl/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

0.8.0-beta1

### Windows Version

windows 11

### Steps to reproduce

Click on the everything toolbar icon

### Expected Behavior

Expected to open up a search window same as the default windows search window

### Actual Behavior

Misaligned and opens the search window in the bottom corner of the screen and the the window sizing in too small

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/113957290/191154674-bf15c01c-bab1-4ac5-b5e5-e073b8ee6488.png)

### Log output

Can not find log prompt appears

**Comment by stnkl** [comment] 2022-09-23 18:33
Thank you. This should be related to your display scaling factor not being 100%. I will mark this as a duplicate of #252.

**Closed by stnkl** 2022-09-23 18:33 UTC
