### ISSUE TITLE
Submenu in context menu not reachable

### ISSUE THREAD

**Issue by 1353604736** [stnkl/EverythingToolbar#60] opened 2021-01-01 07:59 UTC
![0000](https://user-images.githubusercontent.com/12869582/103435498-573f7700-4c4a-11eb-97b5-1234dc4f5790.gif)

**Comment by stnkl** [comment] 2021-01-01 09:24
Could you try disabling all other taskbar toolbars and applications running in the background? It looks like something is stealing focus from the context menu.

**Comment by 1353604736** [comment] 2021-01-01 11:17
> Could you try disabling all other taskbar toolbars and applications running in the background? After disabling toolbars you either have to restart explorer or reboot. It looks like something is stealing focus from the context menu.
> 
> Did you modify the settings file manually or how did you disable animations without access to the menu?

Mouse click, occasionally to the second menu, the chance is very small! !

**Comment by stnkl** [comment] 2021-01-10 16:18
> Could you try disabling all other taskbar toolbars and applications running in the background? After disabling toolbars you either have to restart explorer or reboot.

Did this change anything about the issue?

**Comment by MashukeAlam** [comment] 2021-01-12 12:20
@stnkl @1353604736 I think I know the fix. It has actually nothing to do with everything taskbar but the style how windows manages mouse movement. There is a setting in control panel which says to "activate windows when mouse hovers". Disabling this setting might fix the issue.
![image](https://user-images.githubusercontent.com/42116503/104313821-cc406580-5502-11eb-91f5-b4a27be0b58d.png)

**Comment by stnkl** [comment] 2021-01-12 12:36
> @stnkl @1353604736 I think I know the fix. It has actually nothing to do with everything taskbar but the style how windows manages mouse movement. There is a setting in control panel which says to "activate windows when mouse hovers". Disabling this setting might fix the issue.

Thanks for the input! Unfortunately I can not reproduce the problem by checking said checkmark. Were you able to reproduce it or was that just a guess, @MashukeAlam?

**Comment by MashukeAlam** [comment] 2021-01-12 13:52
@stnkl Similar problems occured to me in other apps with that setting enabled, but I couldn't reproduce the problem with Everything Taskbar. 

Sorry for that. It was just a guess.

By the way, the toolbar icon you mentioned is the icon for an app for writing Chinese. The app is named Sogou Pin Yin [Mac App Store](https://apps.apple.com/id/app/%E6%90%9C%E7%8B%97%E8%BE%93%E5%85%A5%E5%8A%A9%E6%89%8B/id702682966?l=id).

**Comment by stnkl** [comment] 2021-01-17 15:22
I'm closing this issue as it doesn't seem to be caused by EverythingToolbar itself. I'll reopen if needed.

**Closed by stnkl** 2021-01-17 15:22 UTC
Labels: bug
